### PR TITLE
[rs] Derive more traits

### PR DESCRIPTION
**Pull request by demurgos**
Derive the following traits when applicable: `Copy`, `Clone`, `PartialOrd`, `Ord` and `Hash`

### CODE REVIEW

**Comment by demurgos** [comment]
@eddyb Could you check if this is enough for your needs? Do you want more traits?

**Comment by eddyb** [comment]
I had forgotten about `Default` when I listed all those traits before, I think it's the only missing one.

**Comment by demurgos** [comment]
@eddyb What are some of your use cases for `Default`?

Fixed-point number have `Default` in `swf-fixed@0.1.2` (released today). I see why this trait is useful for numeric types, but for most of the types in `swf-tree`, I am not sure which default value to use. For example, I am not sure if there should be a default color, rectangle, filter, etc. These kinds of type may benefit from an explicit initialization. Still, it may be useful for the blend mode (default to normal) or matrices (identity matrix) but I think it depends more on the specific usages. Do you have some types were `Default` should be implement in priority/with which value?

**Comment by eddyb** [comment]
Ah, not manual implementation, but derive, and only when applicable.
The case I care about is a transformation matrix, I think, which is just a bunch of fixed-point values.

**Comment by demurgos** [comment]
@eddyb Ok, I'll add `Default` for the matrices so it defaults to the identity.

For the other types they can be added in other PRs, but initially they should require a manual initialization. For example `const BLACK = SRgb {r: 0, g: 0, b: 0};` instead of `SRgb::default();`.

**Comment by eddyb** [comment]
Ohh, sorry, I'd forgotten how this works:
https://github.com/lykenware/flashback/blob/d9e4987485404e834e3137799288c338fc3250c9/src/timeline.rs#L33

It's an identity transformation, which means some values have to be "one" (multiplicative) and some have to be "zero" (additive).

Any chance you could make the swf-fixed constructors `const fn`? Should be possible on stable Rust nowadays.

Then I can do what you said, and have an identity matrix constant. Sorry for the confusion.

**Comment by demurgos** [comment]
I am merging this PR, this adds `Default` for the types you need.

I marked `from_epsilons` as `const` (`from_value` requires const floating point arithmetic which is not stable yet). I'll send a PR to update this dependency and then release a new version.

**Comment by eddyb** [comment]
I just checked, and the `Matrix` and `ColorTransformWithAlpha` have the exact `Default` impls I need, thanks!

I suppose it does make sense that "identity transform" would be the default, heh, I don't know why I thought in https://github.com/open-flash/swf-tree/pull/19#issuecomment-480189569 that if it's not `#[derive(Default)]`, it's not worth doing.

**Pull request merged**
